[project]
name = "my-sports-models"
version = "0.1.0"
dependencies = [
    "pandas",
    "requests",
    "gspread",
    "oauth2client",
    "pyyaml"
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["shared*", "sports*"]
